// Generated by CoffeeScript 1.7.1
(function() {
  var Environment, anim, bind, delay, init, load, size, state, validateEmail, validatePhone;

  bind = false;

  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  size = function() {
    var h;
    h = $(window).height();
    return imagesLoaded($('body'), function() {});
  };

  Environment = {
    TOUCH_DOWN_EVENT_NAME: 'mousedown touchstart',
    TOUCH_UP_EVENT_NAME: 'mouseup touchend',
    TOUCH_MOVE_EVENT_NAME: 'mousemove touchmove',
    TOUCH_DOUBLE_TAB_EVENT_NAME: 'dblclick dbltap',
    isAndroid: function() {
      return navigator.userAgent.match(/Android/i);
    },
    isBlackBerry: function() {
      return navigator.userAgent.match(/BlackBerry/i);
    },
    isIOS: function() {
      return navigator.userAgent.match(/iPhone|iPad|iPod/i);
    },
    isOpera: function() {
      return navigator.userAgent.match(/Opera Mini/i);
    },
    isWindows: function() {
      return navigator.userAgent.match(/IEMobile/i);
    },
    isMobile: function() {
      return Environment.isAndroid() || Environment.isBlackBerry() || Environment.isIOS() || Environment.isOpera() || Environment.isWindows();
    }
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  validateEmail = function(email) {
    var re;
    re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
  };

  validatePhone = function(phone) {
    var re;
    re = /^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/;
    return re.test(phone);
  };

  anim = function(el, ef, z) {
    if (z == null) {
      z = function() {
        return true;
      };
    }
    return $(el).addClass(ef + ' animated').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function() {
      el.removeClass(ef + ' animated');
      return z();
    });
  };

  state = 0;

  load = function(url) {
    return $.ajax({
      url: url,
      success: function(data) {
        $('body .frame').html($(data).filter('.frame').html());
        anim($('body .frame'), 'fadeIn');
        document.title = $(data).filter('title').text();
        if ($(data).filter('.frame').hasClass('index')) {
          $('.frame').addClass('index');
        } else {
          $('.frame').removeClass('index');
        }
        if ($(data).filter('.frame').hasClass('doctor')) {
          $('.frame').addClass('doctor').removeClass('user');
        } else {
          $('.frame').addClass('user').removeClass('doctor');
        }
        $.scrollTo(0, 500);
        return init();
      }
    });
  };

  init = function() {
    var symptoms_collect, symtpoms_select;
    $(window).on("navigate", function(event, data) {
      return alert();
    });
    if ($('#test-woman').length > 0) {
      $.getScript("/test_women/js/script.js");
    }
    if ($('#test-man').length > 0) {
      $.getScript("/test_man/js/script.js");
    }
    $('a').off('click').on('click', function(e) {
      var History, url;
      if ($(this).parents('#panel, .bx-component-opener').length === 0) {
        History = window.History;
        url = $(this).attr('href');
        e.preventDefault();
        if (History.enabled && url !== '#') {
          if (!$(this).hasClass('no-ajax') && !$(this).hasClass('prevent') && url.charAt(0) !== '#' && url.indexOf('http') < 0) {
            $('body .frame').removeClass('animated fadeIn');
            return History.pushState({
              'url': url
            }, $(this).text(), url);
          } else if (url.indexOf('http') >= 0 || $(this).attr('target') === "_blank") {
            window.open(url, '_blank');
            if ($(this).parents('#locator').length > 0) {
              return $('#locator').modal('hide');
            }
          } else if ($(this).hasClass('no-ajax')) {
            return window.open(url, '_blank');
          }
        }
      }
    });
    $('#doctor').off('shown.bs.modal').on('shown.bs.modal', function() {
      if ($('.frame').hasClass('doctor')) {
        $('#doctor a.back').attr('href', '/');
        $('#doctor a.enter').attr('href', '#');
      } else {
        $('#doctor a.back').attr('href', '#');
        $('#doctor a.enter').attr('href', '/doctors/');
      }
      console.log($('.frame').hasClass('doctor'));
      if ($.cookie('checkbox') === 'true') {
        return $('#doctor .checkbox').addClass('checked');
      }
    });
    $('#symtpoms input').iCheck();
    $('#symptoms-welcome').modal();
    $('#toolbar .trigger').off('click').on('click', function(e) {
      $('#toolbar .nav').toggleClass('open');
      $('body').toggleClass('nav-open');
      return e.preventDefault();
    });
    $('#overlay').off('click scroll touchmove touchstart').on('click scroll touchmove touchstart', function(e) {
      $('#toolbar .nav').removeClass('open');
      $('body').removeClass('nav-open');
      return e.preventDefault();
    });
    symtpoms_select = function(el, hide) {
      var a, answ, c, id, inpt, label, s_id, skip;
      if (hide == null) {
        hide = "true";
      }
      s_id = el.parents('.section').data('id');
      id = el.data('id');
      c = el.data('count');
      label = el.find('h2').text().split('(')[0];
      skip = false;
      if (!el.hasClass('multy')) {
        inpt = el.find('.checked input');
        if (inpt.hasClass('skip')) {
          skip = true;
        } else {
          answ = inpt.data("text").capitalize();
          answ = label + "<strong>" + answ + ".</strong>";
          a = inpt.data('id');
        }
      } else {
        answ = [];
        a = [];
        el.find('.checked input').each(function() {
          var text;
          if ($(this).hasClass('skip')) {
            return skip = true;
          } else {

            /*
            if $(this).data('answer').indexOf("#tanswer#") >= 0 || $(this).data('answer').indexOf("#answer#") >= 0
                text = $(this).data("text")
            else
             */
            text = $(this).data("text");
            answ.push(text);
            return a.push($(this).data("id"));
          }
        });

        /*
        if el.find('input').data('answer').length > 0
            if el.find('input').data('answer').indexOf("#tanswer#") >= 0
                answ[0] = answ[0].capitalize()
                answ = el.find('input').data('answer').replace(/#tanswer#/gi, answ.join(', ')) + '.'
            else if el.find('input').data('answer').indexOf("#answer#") >= 0
                answ = el.find('input').data('answer').replace(/#answer#/gi, answ.join(', '))
            else
                answ = answ.join(' ')
         */
        if (!skip) {
          answ[0] = answ[0].capitalize();
          answ = label + "<strong>" + answ.join(', ') + '</strong>.';
        }
        $("#result .ansver[data-id='" + id + "']").remove();
      }
      if (!skip) {
        $("#result .r" + s_id).append("<div data-id='" + id + "' data-count='" + c + "' data-answer='" + a + "' class='ansver' id='a-" + id + "'>" + answ + "</div>");
      }
      if (hide || skip) {
        el.hide().removeClass('done');
      }
      if (el.parents('.section').find('.question:visible').length === 0) {
        el.parents('.section').hide();
      }
      if ($('.question:visible').length === 0) {
        $('#buttons').removeClass('off');
        symptoms_collect();
      } else {
        if (!$('#buttons').hasClass('off')) {
          $('#buttons').addClass('off');
        }
      }
      symptoms_collect();
      return $("#result .ansver[data-id='" + id + "']").one('click', function(e) {
        id = $(this).data('id');
        if ($(".question[data-id='" + id + "']").parents('.section').is(':hidden')) {
          $(".question[data-id='" + id + "']").parents('.section').show();
        }
        $(".question[data-id='" + id + "']").show();
        $(this).remove();
        return e.preventDefault();
      });
    };
    symptoms_collect = function() {
      var q, test_result;
      test_result = {};
      q = 0;
      $("#result .section").each(function() {
        var a, questions;
        questions = {};
        a = 0;
        $(this).find(".ansver").each(function() {
          questions[$(this).data('count')] = $(this).data('answer');
          return a++;
        });
        test_result[q] = {
          name: $(this).find('h3').text(),
          questions: questions
        };
        return q++;
      });
      $.removeCookie('test_result');
      return $.cookie('test_result', JSON.stringify(test_result));
    };
    $('#symtpoms input').on('ifChecked', function(event, a) {
      var id, index;
      $(this).parents('.question').addClass('done');
      id = $(this).parents('.question').data('id');
      index = id + 1;
      if ($(this).parents('.question').hasClass('multy')) {
        delay(200, function() {
          console.log(index);
          $("#symtpoms .question.done:not(.q-" + id + ")").each(function() {
            return symtpoms_select($(this));
          });
          return $('#symtpoms .question.done').each(function() {
            return symtpoms_select($(this), false);
          });
        });
      } else {
        delay(200, function() {
          return $('#symtpoms .question.done').each(function() {
            return symtpoms_select($(this));
          });
        });
      }
      console.log($("#symtpoms .question:visible").length);
      if ($("#symtpoms .question:visible").length > 1) {
        while (!$("#symtpoms .question[data-id='" + index + "']").length) {
          index++;
        }
        return $("#symtpoms .question[data-id='" + index + "']").addClass('on');
      }
    });
    $('#symtpoms .frame').perfectScrollbar({
      suppressScrollX: true
    });
    $('#symtpoms .question h2').click(function(e) {
      $(this).parents('.question').toggleClass('on');
      $('#symtpoms .question.done').each(function() {
        return symtpoms_select($(this));
      });
      $('#symtpoms .frame').perfectScrollbar('update');
      return e.preventDefault();
    });
    if ($.cookie('checkbox') === "true") {
      $('.checkbox').addClass("checked");
    }
    $('.checkbox').off('click').on('click', function() {
      $(this).toggleClass('checked');
      if ($(this).hasClass('checked')) {
        $.cookie('checkbox', 'true');
      } else {
        $.removeCookie('checkbox');
      }
      return $(this).parent().find('a').toggleClass('no-ajax');
    });
    $('#enter a, a.enter, .landing .enter a').off('click').on('click', function() {
      if (!$(this).parent().find('.checkbox').hasClass("checked")) {
        anim($(this).parent().find('.checkbox'), 'tada');
        return false;
      } else {
        if ($(this).parents('.modal-dialog').length > 0) {
          $('#doctor').modal('hide');
        }
        _gaq.push(['_trackEvent', 'Doctors', 'PopupClick', 'Docs Click Popup']);
        return true;
      }
    });
    $('#toolbar .enter').click(function(e) {
      $('#doctor').modal();
      return e.preventDefault();
    });
    $('#enter.short a').hoverIntent({
      over: function() {
        return $('#enter.short').removeClass('short');
      },
      out: function() {}
    });
    $('#enter').hoverIntent({
      over: function() {
        if ($.cookie('checkbox') === 'true') {
          return $('#enter .checkbox').addClass('checked');
        }
      },
      out: function() {
        if (!$('#enter').hasClass('dont-hide')) {
          return $('#enter').addClass('short');
        }
      }
    });
    $('#faq .block').click(function(ev) {
      var offset;
      if ($(window).width() < 780) {
        if (!$(this).hasClass('open')) {
          $('#faq .block').removeClass('open');
          $(this).toggleClass('open');
          offset = $(this).offset().top;
          $('html, body').animate({
            'scrollTop': offset - $('#toolbar').height() - 14
          }, 300);
        }
      }
      return ev.preventDefault();
    });
    $('#faq .block .text .panel').slimscroll({
      height: function() {
        return $(this).parents('.text').height();
      }
    });
    $('#map').click(function() {
      _gaq.push(['_trackEvent', 'DoctorLocator', 'BannerClick', 'DL BannerMain Click']);
      return $('#locator').modal();
    });
    $('#article.video .icon-play').click(function() {
      var iframe, player;
      $('#article.video iframe').css('opacity', 1);
      $('#article.video .icon-play, .top-title .text').css('opacity', 0);
      iframe = $('#article.video iframe')[0];
      player = $f(iframe);
      return player.api('play');
    });
    if ($('#article .container .col-md-8').height() < $('#article .container .col-md-4.side').height()) {
      while ($('#article .container .col-md-8').height() < $('#article .container .col-md-4.side').height() && $('#article .container .col-md-4.side .block:last').length > 0) {
        $('#article .container .col-md-4.side .block:last').remove();
        if ($('#article .container .col-md-4.side .block:last').length === 0) {
          $('#article .container .col-md-4.side').remove();
        }
      }
    }
    $('#video .icon').click(function() {
      var iframe, player;
      $('#video iframe').css('opacity', 1);
      $('#video .icon').css('opacity', 0);
      iframe = $('#video iframe')[0];
      player = $f(iframe);
      return player.api('play');
    });
    $('[data-toggle=tooltip]').tooltip();
    if (!bind) {
      bind = true;
      History.Adapter.bind(window, 'statechange', function() {
        var State;
        State = History.getState();
        console.log(State);
        return load(State.url);
      });
    }
    return $('#modal-email a').off('click').on('click', function(e) {
      var email, url;
      $('#modal-email input').removeClass('error');
      email = $('#modal-email input').val();
      url = $(this).attr('href');
      console.log(validateEmail(email));
      if (validateEmail(email)) {
        $.ajax({
          url: url,
          data: {
            email: email
          },
          success: function(data) {
            console.log(data);
            if (data === "success") {
              return $('#modal-email').addClass('done');
            }
          }
        });
      } else {
        $('#modal-email input').addClass('error');
      }
      return e.preventDefault();
    });
  };

  $(document).ready(function() {
    $(document).ajaxStart(function() {
      return Pace.restart();
    });
    $(document).ajaxStop(function() {
      return Pace.stop();
    });
    init();
    $('#popup-test').on('hidden.bs.modal', function() {
      return $('#popup-test').removeClass('done');
    });
    return $('body').imagesLoaded(function() {
      $('.frame').css({
        opacity: 1
      }).attr('css', '');
      return $.lockfixed("#article .fix", {
        offset: {
          top: 0,
          bottom: $('#footer').height() + 30
        }
      });
    });
  });

  $(window).resize(function() {
    var x;
    return x = setTimeout(size, 300);
  });

}).call(this);
